leftnav:
- identifier: external--1632447086-1701941700823
  name: page
  params:
    includeLicenseWarning: true
  url: https://www.google.com
  weight: 10
- identifier: external--1632447086-1701941707736
  name: External Link non-ocw
  params:
    includeLicenseWarning: false
  url: https://www.google.com
  weight: 20
- identifier: external--1632447086-1701941710789
  name: External Link ocw
  params:
    includeLicenseWarning: true
  url: https://www.google.com
  weight: 30
