leftnav:
- identifier: external--1632447086-1701941707736
  name: External Link non-ocw
  params:
    includeLicenseWarning: false
  url: https://www.google.com
  weight: 10
- identifier: 69ee1ff5-5131-4bec-87ba-c6c71097c6bf
  name: External Link ocw
  pageRef: /pages/page
  params:
    includeLicenseWarning: true
  weight: 20
