leftnav:
- identifier: 69ee1ff5-5131-4bec-87ba-c6c71097c6bf
  name: page
  pageRef: /pages/page
  weight: 10
- identifier: external--1632447086-1701939612940
  name: External Link non-ocw
  params:
    includeLicenseWarning: true
  url: https://www.google.com
  weight: 20
- identifier: external--1632447086-1701939629033
  name: External Link ocw
  params:
    includeLicenseWarning: false
  url: https://www.google.com
  weight: 30
